# Generated by Django 5.0.6 on 2026-05-30 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('data', models.TextField()),
                ('color', models.IntegerField(choices=[(1, 'Cream'), (2, 'Mint'), (3, 'Lavender'), (4, 'Light Green'), (5, 'Pink'), (6, 'Sky Blue'), (7, 'Yellow'), (8, 'Teal'), (9, 'Light Blue')], default=1)),
                ('date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='entries.entry')),
            ],
        ),
    ]
